=== 5genesis/katana-slice_manager/katana-schemas/supported_sst_model.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "definitions": {
    "ns": {
      "type": "object",
      "description": "A Network Service",
      "properties":{
        "nfvo-id":{
          "type": "string",
          "description": "The NFVO that will manage the life cycle of the NS"
        },
        "nsd-id": {
          "type": "string",
          "description": "The NSD id as defined on the NFVO"
        },
        "ns-name": {
          "type": "string",
          "description": "The name of the NS"
        },
        "placement": {
          "type": "number",
          "enum": [0, 1],
          "description": "1: Core, 2: Edge"
        },
        "ems-id": {
          "type": "string",
          "description": "Optional - Defines the EMS that is responsible for D1&2 configuration"
        },
        "optional":{
          "type": "boolean"
        }
      }
    },
    "pnf": {
      "type": "object",
      "description": "A Physical Network Service",
      "properties": {
        "ns-name": {
          "type": "string",
          "description": "The name of the PNF"
        },
        "ems-id": {
          "type": "string",
          "description": "Optional - Defines the EMS that is responsible for D1&2 configuration"
        },
        "pdu-id": {
          "type": "string",
          "description": "The Physical Device Unit that will be used for the PNF"
        },
        "optional":{
          "type": "boolean"
        }
      }
    }
  },

  "type": "object",
  "description": "A supported slice by the platform",
  "properties": {
    "sst": {
      "type": "number",
      "enum": [1, 2, 3],
      "description": "1: embb, 2: urllc, 3: iot"
    },
    "sd": {
      "type": "number",
      "description": "Service Differentiator - Optional information that complements the Slice/Service type(s) to differentiate amongst multiple Network Slices of the same SST"
    },
    "name": {
      "type": "string",
      "description": "Optional name for the SST"
    },
    "supported_locations": {
      "type": "array",
      "description" : "A list of the supported edge locations of the platform for that slice",
      "items": {
        "type": "string",
        "description": "A location"
      }
    },
    "ns_list": {
      "type": "array",
      "description": "A list of the NSs that will be part of the slice",
      "items": {
        "$ref": "#/definitions/ns"
      }
    },
    "pnf_list": {
      "type": "array",
      "description": "A list of the PNFs that will be part of the slice",
      "items": {
        "$ref": "#/definitions/pnf"
      }
    }
  }
}

=== 5genesis/katana-slice_manager/example_config_files/Slices/sst_O5GCore_urllc.json
{
    "sst": 2,
    "name": "5GCore",
    "supported_locations": ["minilab", "library", "cosmote"],
    "ns_list":[
        {
            "nfvo-id": "OSM6",
            "nsd-id": "2ca6ab45-e9d5-4397-932b-787886c4984e",
            "ns-name": "5GCore_GW_nsd",
            "placement": 1,
            "optional": false
        },
        {
            "nfvo-id": "OSM6",
            "nsd-id": "e47bb529-2c38-4b16-969a-fa9661f54824",
            "ns-name": "5GCore_MME-HSS_nsd",
            "placement": 0,
            "optional": false
        },
        {
            "nfvo-id": "OSM6",
            "nsd-id": "9add5eeb-0cdd-46b5-a551-eedb133e0432",
            "ns-name": "5GCore_PCRF_nsd",
            "placement": 1,
            "optional": true
        },
        {
            "nfvo-id": "OSM5",
            "nsd-id": "65373e5a-679d-46b7-898a-e304652e5102",
            "ns-name": "dummy_ns",
            "placement": 1,
            "optional": true
        }
    ],
    "pnf_list":[]
}

=== 5genesis/katana-slice_manager/example_config_files/Slices/sst_O5GCore_embb.json
{
    "sst": 1,
    "name": "5GCore",
    "supported_locations": [],
    "ns_list":[
        {
            "nfvo-id": "OSM6",
            "nsd-id": "2ca6ab45-e9d5-4397-932b-787886c4984e",
            "ns-name": "5GCore_GW_nsd",
            "placement": 0,
            "optional": false
        },
        {
            "nfvo-id": "OSM6",
            "nsd-id": "e47bb529-2c38-4b16-969a-fa9661f54824",
            "ns-name": "5GCore_MME-HSS_nsd",
            "placement": 0,
            "optional": false
        },
        {
            "nfvo-id": "OSM6",
            "nsd-id": "9add5eeb-0cdd-46b5-a551-eedb133e0432",
            "ns-name": "5GCore_PCRF_nsd",
            "placement": 0,
            "optional": true
        },
        {
            "nfvo-id": "OSM6",
            "nsd-id": "tbd",
            "ns-name": "dummy_ns",
            "placement": 0,
            "optional": true
        }
    ],
    "pnf_list":[]
}

=== 5genesis/katana-slice_manager/example_config_files/Slices/sst_dummy_embb.json
{
    "sst": 1,
    "name": "dummy",
    "supported_locations": [],
    "ns_list":[
        {
            "nfvo-id": "OSM6",
            "nsd-id": "8aa747b5-26e5-4ed9-9f85-da153c92b2bf",
            "ns-name": "dummy_ns",
            "placement": 0,
            "optional": true
        }
    ],
    "pnf_list":[]
}
